### ISSUE TITLE
[Minor] Misalignment of "img under h3 element in ul li" on the Dementia Information page

### ISSUE THREAD

**Issue by tangsta** [Hamza-Alwani/CSE3311_Alzheimers#1]
Redo/Fix the problem to make the page look better.

Files:
DementiaComponent.js
dementia_information.css

![misalign](https://user-images.githubusercontent.com/21026400/92556039-9296df80-f22e-11ea-802f-612f28a56658.PNG)

**Comment by Hamza-Alwani** [comment]
damn just roasted the shit out of my CSS files

**Comment by tangsta** [comment]
what when LMAO

**Comment by Hamza-Alwani** [comment]
fixed
