### ISSUE TITLE
footer doesnt work on mobile

### ISSUE THREAD

**Issue by Hamza-Alwani** [Hamza-Alwani/CSE3311_Alzheimers#11]
![Screenshot 2020-09-10 152935](https://user-images.githubusercontent.com/40344601/92800605-743dfa80-f37a-11ea-83e7-363f74c1af2e.png)

**Comment by tangsta** [comment]
fixed with branch merge "bugfix-footer" , the main content will now fill the remaining space of the screen and then the foot will push itself down against it
